[package]
name = "djl"
version = "0.1.0"
authors = ["Frank Liu <frankfliu2000@gmail.com>"]
edition = "2018"

[dependencies]
jni = "0.19.0"
tokenizers = { path = "../../vendors/tokenizers/tokenizers", version = "*", features = ["http"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[lib]
crate-type = ["staticlib", "cdylib"]
