name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  instrumented_tests:
    name: Run Scripts
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: amyu/setup-android@v3
        with:
          sdk-version: 34
          build-tools-version: 34.0.0
          cmake-version: 3.10.2.4988404
          ndk-version: 26.1.10909125
      
      - name: checkout
        uses: actions/checkout@v2

      - name: rust toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install cargo ndk
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-ndk

      - name: setup build targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android aarch64-apple-ios x86_64-apple-ios

      - name: build android
        run: ./gradlew cargoBuild
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125
          TOOLCHAIN: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64
          RANLIB: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ranlib

      - name: build iso
        run: cargo build --target=aarch64-apple-ios && cargo build --target=x86_64-apple-ios
