name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  instrumented_tests:
    name: Run Scripts
    runs-on: macos-latest

    steps:
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log

      - name: checkout
        uses: actions/checkout@v2

      - name: rust toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install cargo ndk
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-ndk

      - name: setup build targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android aarch64-apple-ios x86_64-apple-ios

      - name: build android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew cargoBuild

      - name: build iso
        with:
          script: cargo build --target=aarch64-apple-ios && cargo build --target=x86_64-apple-ios
